# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nano.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1037, 826)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Curve = QtWidgets.QGroupBox(self.centralwidget)
        self.Curve.setObjectName("Curve")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Curve)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.Curve)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.curve_segment = QtWidgets.QSpinBox(self.Curve)
        self.curve_segment.setMaximum(9)
        self.curve_segment.setProperty("value", 1)
        self.curve_segment.setObjectName("curve_segment")
        self.horizontalLayout_6.addWidget(self.curve_segment)
        self.verticalLayout_6.addWidget(self.Curve)
        self.mainlist = QtWidgets.QTreeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainlist.sizePolicy().hasHeightForWidth())
        self.mainlist.setSizePolicy(sizePolicy)
        self.mainlist.setObjectName("mainlist")
        self.verticalLayout_6.addWidget(self.mainlist)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.reset_include = QtWidgets.QRadioButton(self.groupBox_4)
        self.reset_include.setChecked(True)
        self.reset_include.setObjectName("reset_include")
        self.verticalLayout_2.addWidget(self.reset_include)
        self.reset_activate = QtWidgets.QRadioButton(self.groupBox_4)
        self.reset_activate.setObjectName("reset_activate")
        self.verticalLayout_2.addWidget(self.reset_activate)
        self.reset_all = QtWidgets.QPushButton(self.groupBox_4)
        self.reset_all.setObjectName("reset_all")
        self.verticalLayout_2.addWidget(self.reset_all)
        self.verticalLayout_6.addWidget(self.groupBox_4)
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.open_o11new = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_o11new.setChecked(False)
        self.open_o11new.setObjectName("open_o11new")
        self.verticalLayout_3.addWidget(self.open_o11new)
        self.open_o11old = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_o11old.setObjectName("open_o11old")
        self.verticalLayout_3.addWidget(self.open_o11old)
        self.open_nanosurf = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_nanosurf.setChecked(True)
        self.open_nanosurf.setObjectName("open_nanosurf")
        self.verticalLayout_3.addWidget(self.open_nanosurf)
        self.open_selectFolder = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.open_selectFolder.setFont(font)
        self.open_selectFolder.setObjectName("open_selectFolder")
        self.verticalLayout_3.addWidget(self.open_selectFolder)
        self.open_load = QtWidgets.QPushButton(self.groupBox_12)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.open_load.setFont(font)
        self.open_load.setObjectName("open_load")
        self.verticalLayout_3.addWidget(self.open_load)
        self.verticalLayout_6.addWidget(self.groupBox_12)
        self.horizontalLayout_11.addLayout(self.verticalLayout_6)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.view_all = QtWidgets.QRadioButton(self.groupBox)
        self.view_all.setStyleSheet("color: red;")
        self.view_all.setChecked(True)
        self.view_all.setObjectName("view_all")
        self.horizontalLayout_4.addWidget(self.view_all)
        self.view_included = QtWidgets.QRadioButton(self.groupBox)
        self.view_included.setStyleSheet("color: blue;")
        self.view_included.setObjectName("view_included")
        self.horizontalLayout_4.addWidget(self.view_included)
        self.view_active = QtWidgets.QRadioButton(self.groupBox)
        self.view_active.setObjectName("view_active")
        self.horizontalLayout_4.addWidget(self.view_active)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.fdistance = PlotWidget(self.widget)
        self.fdistance.setObjectName("fdistance")
        self.verticalLayout_7.addWidget(self.fdistance)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.toggle_excluded = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_excluded.setStyleSheet("color: red;")
        self.toggle_excluded.setChecked(True)
        self.toggle_excluded.setObjectName("toggle_excluded")
        self.horizontalLayout_5.addWidget(self.toggle_excluded)
        self.toggle_included = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_included.setStyleSheet("color: blue;")
        self.toggle_included.setObjectName("toggle_included")
        self.horizontalLayout_5.addWidget(self.toggle_included)
        self.toggle_activated = QtWidgets.QRadioButton(self.groupBox_2)
        self.toggle_activated.setObjectName("toggle_activated")
        self.horizontalLayout_5.addWidget(self.toggle_activated)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_6 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.filter_prominency = QtWidgets.QGroupBox(self.groupBox_6)
        self.filter_prominency.setCheckable(True)
        self.filter_prominency.setChecked(False)
        self.filter_prominency.setObjectName("filter_prominency")
        self.formLayout = QtWidgets.QFormLayout(self.filter_prominency)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.filter_prominency)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.filter_prominency_prominency = QtWidgets.QSpinBox(self.filter_prominency)
        self.filter_prominency_prominency.setMinimum(1)
        self.filter_prominency_prominency.setMaximum(999)
        self.filter_prominency_prominency.setSingleStep(10)
        self.filter_prominency_prominency.setProperty("value", 40)
        self.filter_prominency_prominency.setObjectName("filter_prominency_prominency")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filter_prominency_prominency)
        self.label_4 = QtWidgets.QLabel(self.filter_prominency)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.filter_prominency_minfreq = QtWidgets.QSpinBox(self.filter_prominency)
        self.filter_prominency_minfreq.setMinimum(3)
        self.filter_prominency_minfreq.setMaximum(999)
        self.filter_prominency_minfreq.setSingleStep(5)
        self.filter_prominency_minfreq.setProperty("value", 25)
        self.filter_prominency_minfreq.setObjectName("filter_prominency_minfreq")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filter_prominency_minfreq)
        self.label_5 = QtWidgets.QLabel(self.filter_prominency)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.filter_prominency_band = QtWidgets.QSpinBox(self.filter_prominency)
        self.filter_prominency_band.setMinimum(1)
        self.filter_prominency_band.setMaximum(999)
        self.filter_prominency_band.setSingleStep(5)
        self.filter_prominency_band.setProperty("value", 30)
        self.filter_prominency_band.setObjectName("filter_prominency_band")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.filter_prominency_band)
        self.verticalLayout_5.addWidget(self.filter_prominency)
        self.filter_fsmooth = QtWidgets.QGroupBox(self.groupBox_6)
        self.filter_fsmooth.setCheckable(True)
        self.filter_fsmooth.setChecked(False)
        self.filter_fsmooth.setObjectName("filter_fsmooth")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.filter_fsmooth)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.filter_fsmooth_savitzky = QtWidgets.QRadioButton(self.filter_fsmooth)
        self.filter_fsmooth_savitzky.setChecked(True)
        self.filter_fsmooth_savitzky.setObjectName("filter_fsmooth_savitzky")
        self.verticalLayout_4.addWidget(self.filter_fsmooth_savitzky)
        self.filter_median = QtWidgets.QRadioButton(self.filter_fsmooth)
        self.filter_median.setObjectName("filter_median")
        self.verticalLayout_4.addWidget(self.filter_median)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.filter_fsmooth)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.filter_window = QtWidgets.QSpinBox(self.filter_fsmooth)
        self.filter_window.setMinimum(3)
        self.filter_window.setMaximum(999)
        self.filter_window.setSingleStep(2)
        self.filter_window.setProperty("value", 25)
        self.filter_window.setObjectName("filter_window")
        self.horizontalLayout_3.addWidget(self.filter_window)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addWidget(self.filter_fsmooth)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_7 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.contact_window = QtWidgets.QSpinBox(self.groupBox_7)
        self.contact_window.setMinimum(3)
        self.contact_window.setMaximum(9999)
        self.contact_window.setSingleStep(2)
        self.contact_window.setProperty("value", 50)
        self.contact_window.setObjectName("contact_window")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.contact_window)
        self.label_7 = QtWidgets.QLabel(self.groupBox_7)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.contact_offset = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.contact_offset.setMinimum(-999.99)
        self.contact_offset.setMaximum(999.99)
        self.contact_offset.setProperty("value", 1.5)
        self.contact_offset.setObjectName("contact_offset")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contact_offset)
        self.label_8 = QtWidgets.QLabel(self.groupBox_7)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.contact_threshold = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.contact_threshold.setMinimum(-999.99)
        self.contact_threshold.setMaximum(999.99)
        self.contact_threshold.setProperty("value", 10.0)
        self.contact_threshold.setObjectName("contact_threshold")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.contact_threshold)
        self.verticalLayout.addWidget(self.groupBox_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.stats_R = QtWidgets.QLabel(self.groupBox_3)
        self.stats_R.setObjectName("stats_R")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.stats_R)
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.stats_k = QtWidgets.QLabel(self.groupBox_3)
        self.stats_k.setObjectName("stats_k")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stats_k)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.stats_ne = QtWidgets.QLabel(self.groupBox_3)
        self.stats_ne.setStyleSheet("color: red;")
        self.stats_ne.setObjectName("stats_ne")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.stats_ne)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.stats_ni = QtWidgets.QLabel(self.groupBox_3)
        self.stats_ni.setStyleSheet("color: blue;")
        self.stats_ni.setObjectName("stats_ni")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.stats_ni)
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.stats_na = QtWidgets.QLabel(self.groupBox_3)
        self.stats_na.setStyleSheet("")
        self.stats_na.setObjectName("stats_na")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stats_na)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_5 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.save_curves = QtWidgets.QPushButton(self.groupBox_5)
        self.save_curves.setObjectName("save_curves")
        self.horizontalLayout_8.addWidget(self.save_curves)
        self.save_data = QtWidgets.QPushButton(self.groupBox_5)
        self.save_data.setObjectName("save_data")
        self.horizontalLayout_8.addWidget(self.save_data)
        self.verticalLayout_8.addWidget(self.groupBox_5)
        self.indentation = PlotWidget(self.widget1)
        self.indentation.setObjectName("indentation")
        self.verticalLayout_8.addWidget(self.indentation)
        self.groupBox_8 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_8.setCheckable(True)
        self.groupBox_8.setChecked(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.histogram_min = QtWidgets.QSpinBox(self.groupBox_8)
        self.histogram_min.setMinimum(-99999)
        self.histogram_min.setMaximum(99999)
        self.histogram_min.setSingleStep(1000)
        self.histogram_min.setObjectName("histogram_min")
        self.horizontalLayout_2.addWidget(self.histogram_min)
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.histogram_max = QtWidgets.QSpinBox(self.groupBox_8)
        self.histogram_max.setMaximum(999999)
        self.histogram_max.setSingleStep(1000)
        self.histogram_max.setProperty("value", 50000)
        self.histogram_max.setObjectName("histogram_max")
        self.horizontalLayout_2.addWidget(self.histogram_max)
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.histogram_bins = QtWidgets.QSpinBox(self.groupBox_8)
        self.histogram_bins.setMinimum(1)
        self.histogram_bins.setProperty("value", 10)
        self.histogram_bins.setObjectName("histogram_bins")
        self.horizontalLayout_2.addWidget(self.histogram_bins)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.histo = PlotWidget(self.widget1)
        self.histo.setObjectName("histo")
        self.horizontalLayout_10.addWidget(self.histo)
        self.scatter = PlotWidget(self.widget1)
        self.scatter.setObjectName("scatter")
        self.horizontalLayout_10.addWidget(self.scatter)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.groupBox_9 = QtWidgets.QGroupBox(self.widget1)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.groupBox_9)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.fit_indentation = QtWidgets.QSpinBox(self.groupBox_9)
        self.fit_indentation.setMinimum(10)
        self.fit_indentation.setMaximum(19999)
        self.fit_indentation.setProperty("value", 800)
        self.fit_indentation.setObjectName("fit_indentation")
        self.horizontalLayout_9.addWidget(self.fit_indentation)
        self.fit_center = QtWidgets.QLabel(self.groupBox_9)
        self.fit_center.setStyleSheet("font-weight:bold;")
        self.fit_center.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.fit_center.setObjectName("fit_center")
        self.horizontalLayout_9.addWidget(self.fit_center)
        self.label_23 = QtWidgets.QLabel(self.groupBox_9)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_9.addWidget(self.label_23)
        self.fit_std = QtWidgets.QLabel(self.groupBox_9)
        self.fit_std.setStyleSheet("font-weight:bold;")
        self.fit_std.setObjectName("fit_std")
        self.horizontalLayout_9.addWidget(self.fit_std)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.Data = QtWidgets.QGroupBox(self.widget1)
        self.Data.setObjectName("Data")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Data)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_18 = QtWidgets.QLabel(self.Data)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_7.addWidget(self.label_18)
        self.data_average = QtWidgets.QLabel(self.Data)
        self.data_average.setStyleSheet("font-weight:bold;")
        self.data_average.setAlignment(QtCore.Qt.AlignCenter)
        self.data_average.setObjectName("data_average")
        self.horizontalLayout_7.addWidget(self.data_average)
        self.label_20 = QtWidgets.QLabel(self.Data)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_7.addWidget(self.label_20)
        self.data_std = QtWidgets.QLabel(self.Data)
        self.data_std.setStyleSheet("font-weight:bold;")
        self.data_std.setAlignment(QtCore.Qt.AlignCenter)
        self.data_std.setObjectName("data_std")
        self.horizontalLayout_7.addWidget(self.data_std)
        self.verticalLayout_8.addWidget(self.Data)
        self.horizontalLayout_11.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nano2020"))
        self.Curve.setTitle(_translate("MainWindow", "Curve"))
        self.label.setText(_translate("MainWindow", "Segment"))
        self.mainlist.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Reset"))
        self.reset_include.setText(_translate("MainWindow", "Include"))
        self.reset_activate.setText(_translate("MainWindow", "Activate"))
        self.reset_all.setText(_translate("MainWindow", "ALL"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Open"))
        self.open_o11new.setText(_translate("MainWindow", "Optics11 - NEW"))
        self.open_o11old.setText(_translate("MainWindow", "Optics11 - OLD"))
        self.open_nanosurf.setText(_translate("MainWindow", "Nanosurf export"))
        self.open_selectFolder.setText(_translate("MainWindow", "Select Root Folder"))
        self.open_selectFolder.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.open_load.setText(_translate("MainWindow", "Load"))
        self.open_load.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.groupBox.setTitle(_translate("MainWindow", "View"))
        self.view_all.setText(_translate("MainWindow", "All"))
        self.view_included.setText(_translate("MainWindow", "Included"))
        self.view_active.setText(_translate("MainWindow", "Active"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Toggle"))
        self.toggle_excluded.setText(_translate("MainWindow", "Excluded"))
        self.toggle_included.setText(_translate("MainWindow", "Included"))
        self.toggle_activated.setText(_translate("MainWindow", "Activated"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Filter"))
        self.filter_prominency.setTitle(_translate("MainWindow", "Prominency"))
        self.label_3.setText(_translate("MainWindow", "Prominency"))
        self.label_4.setText(_translate("MainWindow", "Min Freq"))
        self.label_5.setText(_translate("MainWindow", "Band"))
        self.filter_fsmooth.setTitle(_translate("MainWindow", "F-Smooth"))
        self.filter_fsmooth_savitzky.setText(_translate("MainWindow", "Savitzky-Golay"))
        self.filter_median.setText(_translate("MainWindow", "Median"))
        self.label_2.setText(_translate("MainWindow", "Window"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Contact"))
        self.label_6.setText(_translate("MainWindow", "Window"))
        self.label_7.setText(_translate("MainWindow", "Offset"))
        self.label_8.setText(_translate("MainWindow", "Threshold"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Stats"))
        self.label_9.setText(_translate("MainWindow", "R"))
        self.stats_R.setText(_translate("MainWindow", "3200 nm"))
        self.label_17.setText(_translate("MainWindow", "k"))
        self.stats_k.setText(_translate("MainWindow", "0.05 N/m"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>N<span style=\" vertical-align:sub;\">excluded</span></p></body></html>"))
        self.stats_ne.setText(_translate("MainWindow", "127"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>N<span style=\" vertical-align:sub;\">included</span></p></body></html>"))
        self.stats_ni.setText(_translate("MainWindow", "52"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p>N<span style=\" vertical-align:sub;\">activated</span></p></body></html>"))
        self.stats_na.setText(_translate("MainWindow", "63"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Save"))
        self.save_curves.setText(_translate("MainWindow", "Curves"))
        self.save_data.setText(_translate("MainWindow", "Data"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Histogram"))
        self.label_12.setText(_translate("MainWindow", "Range"))
        self.label_13.setText(_translate("MainWindow", "-"))
        self.label_14.setText(_translate("MainWindow", "Bins"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Fit"))
        self.label_16.setText(_translate("MainWindow", "Indentation [nm]"))
        self.fit_center.setText(_translate("MainWindow", "7427"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>±</p></body></html>"))
        self.fit_std.setText(_translate("MainWindow", "352"))
        self.Data.setTitle(_translate("MainWindow", "Data"))
        self.label_18.setText(_translate("MainWindow", "Average [Pa]"))
        self.data_average.setText(_translate("MainWindow", "5723"))
        self.label_20.setText(_translate("MainWindow", "Std [Pa]"))
        self.data_std.setText(_translate("MainWindow", "345"))
from pyqtgraph import PlotWidget
