# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Chiaro.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1332, 741)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.switcher = QtWidgets.QStackedWidget(self.centralwidget)
        self.switcher.setObjectName("switcher")
        self.stackedWidgetPage1 = QtWidgets.QWidget()
        self.stackedWidgetPage1.setObjectName("stackedWidgetPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.stackedWidgetPage1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_6 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.b1_start = QtWidgets.QSpinBox(self.groupBox_6)
        self.b1_start.setMinimum(-100000)
        self.b1_start.setMaximum(100000)
        self.b1_start.setSingleStep(10)
        self.b1_start.setProperty("value", -15000)
        self.b1_start.setObjectName("b1_start")
        self.gridLayout_2.addWidget(self.b1_start, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_6)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.b1_end = QtWidgets.QSpinBox(self.groupBox_6)
        self.b1_end.setMinimum(-100000)
        self.b1_end.setMaximum(100000)
        self.b1_end.setSingleStep(10)
        self.b1_end.setProperty("value", 15000)
        self.b1_end.setObjectName("b1_end")
        self.gridLayout_2.addWidget(self.b1_end, 1, 1, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.b1_yAlign = QtWidgets.QSpinBox(self.groupBox_7)
        self.b1_yAlign.setMinimum(50)
        self.b1_yAlign.setMaximum(19999)
        self.b1_yAlign.setProperty("value", 3000)
        self.b1_yAlign.setObjectName("b1_yAlign")
        self.verticalLayout_8.addWidget(self.b1_yAlign)
        self.b1_yAlignButton = QtWidgets.QPushButton(self.groupBox_7)
        self.b1_yAlignButton.setObjectName("b1_yAlignButton")
        self.verticalLayout_8.addWidget(self.b1_yAlignButton)
        self.b1_forwardSegment = QtWidgets.QSlider(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1_forwardSegment.sizePolicy().hasHeightForWidth())
        self.b1_forwardSegment.setSizePolicy(sizePolicy)
        self.b1_forwardSegment.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.b1_forwardSegment.setMinimum(0)
        self.b1_forwardSegment.setMaximum(1)
        self.b1_forwardSegment.setProperty("value", 0)
        self.b1_forwardSegment.setTracking(True)
        self.b1_forwardSegment.setOrientation(QtCore.Qt.Horizontal)
        self.b1_forwardSegment.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.b1_forwardSegment.setTickInterval(1)
        self.b1_forwardSegment.setObjectName("b1_forwardSegment")
        self.verticalLayout_8.addWidget(self.b1_forwardSegment)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_16 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.b1_minmax = QtWidgets.QDoubleSpinBox(self.groupBox_16)
        self.b1_minmax.setProperty("value", 5.0)
        self.b1_minmax.setObjectName("b1_minmax")
        self.verticalLayout_16.addWidget(self.b1_minmax)
        self.b1_doInvalidate = QtWidgets.QPushButton(self.groupBox_16)
        self.b1_doInvalidate.setObjectName("b1_doInvalidate")
        self.verticalLayout_16.addWidget(self.b1_doInvalidate)
        self.horizontalLayout_3.addWidget(self.groupBox_16)
        self.groupBox = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.b1_redblack = QtWidgets.QRadioButton(self.groupBox)
        self.b1_redblack.setChecked(True)
        self.b1_redblack.setObjectName("b1_redblack")
        self.verticalLayout_9.addWidget(self.b1_redblack)
        self.b1_black = QtWidgets.QRadioButton(self.groupBox)
        self.b1_black.setObjectName("b1_black")
        self.verticalLayout_9.addWidget(self.b1_black)
        self.b1_red = QtWidgets.QRadioButton(self.groupBox)
        self.b1_red.setObjectName("b1_red")
        self.verticalLayout_9.addWidget(self.b1_red)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_12 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.open_o11new = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_o11new.setChecked(False)
        self.open_o11new.setObjectName("open_o11new")
        self.verticalLayout_7.addWidget(self.open_o11new)
        self.open_o11old = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_o11old.setObjectName("open_o11old")
        self.verticalLayout_7.addWidget(self.open_o11old)
        self.open_nanosurf = QtWidgets.QRadioButton(self.groupBox_12)
        self.open_nanosurf.setChecked(True)
        self.open_nanosurf.setObjectName("open_nanosurf")
        self.verticalLayout_7.addWidget(self.open_nanosurf)
        self.horizontalLayout_3.addWidget(self.groupBox_12)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.groupBox_9 = QtWidgets.QGroupBox(self.stackedWidgetPage1)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.b1tob2 = QtWidgets.QPushButton(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1tob2.sizePolicy().hasHeightForWidth())
        self.b1tob2.setSizePolicy(sizePolicy)
        self.b1tob2.setObjectName("b1tob2")
        self.horizontalLayout_2.addWidget(self.b1tob2)
        self.b1_generate = QtWidgets.QPushButton(self.groupBox_9)
        self.b1_generate.setObjectName("b1_generate")
        self.horizontalLayout_2.addWidget(self.b1_generate)
        self.sl_load = QtWidgets.QPushButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sl_load.setFont(font)
        self.sl_load.setObjectName("sl_load")
        self.horizontalLayout_2.addWidget(self.sl_load)
        self.b1_selectFolder = QtWidgets.QPushButton(self.groupBox_9)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.b1_selectFolder.setFont(font)
        self.b1_selectFolder.setObjectName("b1_selectFolder")
        self.horizontalLayout_2.addWidget(self.b1_selectFolder)
        self.horizontalLayout_3.addWidget(self.groupBox_9)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.stackedWidgetPage1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.b1_mainList = QtWidgets.QTreeWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1_mainList.sizePolicy().hasHeightForWidth())
        self.b1_mainList.setSizePolicy(sizePolicy)
        self.b1_mainList.setObjectName("b1_mainList")
        self.b1_graph = PlotWidget(self.splitter)
        self.b1_graph.setObjectName("b1_graph")
        self.b1_Alpha = QtWidgets.QSlider(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1_Alpha.sizePolicy().hasHeightForWidth())
        self.b1_Alpha.setSizePolicy(sizePolicy)
        self.b1_Alpha.setMaximum(255)
        self.b1_Alpha.setProperty("value", 30)
        self.b1_Alpha.setOrientation(QtCore.Qt.Vertical)
        self.b1_Alpha.setObjectName("b1_Alpha")
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(1, 1)
        self.switcher.addWidget(self.stackedWidgetPage1)
        self.stackedWidgetPage2 = QtWidgets.QWidget()
        self.stackedWidgetPage2.setObjectName("stackedWidgetPage2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stackedWidgetPage2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.stackedWidgetPage2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.b2_vOriginal = QtWidgets.QRadioButton(self.groupBox_2)
        self.b2_vOriginal.setChecked(False)
        self.b2_vOriginal.setObjectName("b2_vOriginal")
        self.horizontalLayout_4.addWidget(self.b2_vOriginal)
        self.b2_vFiltered = QtWidgets.QRadioButton(self.groupBox_2)
        self.b2_vFiltered.setChecked(True)
        self.b2_vFiltered.setObjectName("b2_vFiltered")
        self.horizontalLayout_4.addWidget(self.b2_vFiltered)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.b2_segment = QtWidgets.QSlider(self.stackedWidgetPage2)
        self.b2_segment.setMaximum(500)
        self.b2_segment.setPageStep(1)
        self.b2_segment.setTracking(True)
        self.b2_segment.setOrientation(QtCore.Qt.Horizontal)
        self.b2_segment.setObjectName("b2_segment")
        self.horizontalLayout_7.addWidget(self.b2_segment)
        self.groupBox_10 = QtWidgets.QGroupBox(self.stackedWidgetPage2)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.b2_save = QtWidgets.QPushButton(self.groupBox_10)
        self.b2_save.setObjectName("b2_save")
        self.horizontalLayout_10.addWidget(self.b2_save)
        self.b2_b2tob3 = QtWidgets.QPushButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2_b2tob3.sizePolicy().hasHeightForWidth())
        self.b2_b2tob3.setSizePolicy(sizePolicy)
        self.b2_b2tob3.setObjectName("b2_b2tob3")
        self.horizontalLayout_10.addWidget(self.b2_b2tob3)
        self.horizontalLayout_7.addWidget(self.groupBox_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b2_Alpha = QtWidgets.QSlider(self.stackedWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2_Alpha.sizePolicy().hasHeightForWidth())
        self.b2_Alpha.setSizePolicy(sizePolicy)
        self.b2_Alpha.setMaximum(255)
        self.b2_Alpha.setProperty("value", 30)
        self.b2_Alpha.setOrientation(QtCore.Qt.Vertical)
        self.b2_Alpha.setObjectName("b2_Alpha")
        self.horizontalLayout_6.addWidget(self.b2_Alpha)
        self.b2_plot_all = PlotWidget(self.stackedWidgetPage2)
        self.b2_plot_all.setObjectName("b2_plot_all")
        self.horizontalLayout_6.addWidget(self.b2_plot_all)
        self.b2_plot_elasto = PlotWidget(self.stackedWidgetPage2)
        self.b2_plot_elasto.setObjectName("b2_plot_elasto")
        self.horizontalLayout_6.addWidget(self.b2_plot_elasto)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.b2_plot_one = PlotWidget(self.stackedWidgetPage2)
        self.b2_plot_one.setObjectName("b2_plot_one")
        self.verticalLayout_2.addWidget(self.b2_plot_one)
        self.b2_plot_two = PlotWidget(self.stackedWidgetPage2)
        self.b2_plot_two.setObjectName("b2_plot_two")
        self.verticalLayout_2.addWidget(self.b2_plot_two)
        self.b2_plot_three = PlotWidget(self.stackedWidgetPage2)
        self.b2_plot_three.setObjectName("b2_plot_three")
        self.verticalLayout_2.addWidget(self.b2_plot_three)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.b2_delete = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.b2_delete.setObjectName("b2_delete")
        self.horizontalLayout_9.addWidget(self.b2_delete)
        self.b2_deleteAllInvalid = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.b2_deleteAllInvalid.setObjectName("b2_deleteAllInvalid")
        self.horizontalLayout_9.addWidget(self.b2_deleteAllInvalid)
        self.b2_CropCurves = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.b2_CropCurves.setObjectName("b2_CropCurves")
        self.horizontalLayout_9.addWidget(self.b2_CropCurves)
        self.b2_doFilter = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.b2_doFilter.setObjectName("b2_doFilter")
        self.horizontalLayout_9.addWidget(self.b2_doFilter)
        self.horizontalLayout.addLayout(self.horizontalLayout_9)
        self.groupBox_4 = QtWidgets.QGroupBox(self.stackedWidgetPage2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboContact = QtWidgets.QComboBox(self.groupBox_4)
        self.comboContact.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.comboContact.setObjectName("comboContact")
        self.comboContact.addItem("")
        self.comboContact.addItem("")
        self.comboContact.addItem("")
        self.comboContact.addItem("")
        self.verticalLayout_10.addWidget(self.comboContact)
        self.b2_doContactPoint = QtWidgets.QPushButton(self.groupBox_4)
        self.b2_doContactPoint.setObjectName("b2_doContactPoint")
        self.verticalLayout_10.addWidget(self.b2_doContactPoint)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.b2_DoElasto = QtWidgets.QPushButton(self.stackedWidgetPage2)
        self.b2_DoElasto.setObjectName("b2_DoElasto")
        self.horizontalLayout.addWidget(self.b2_DoElasto)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.switcher.addWidget(self.stackedWidgetPage2)
        self.stackedWidgetPage3 = QtWidgets.QWidget()
        self.stackedWidgetPage3.setObjectName("stackedWidgetPage3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stackedWidgetPage3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_15 = QtWidgets.QGroupBox(self.stackedWidgetPage3)
        self.groupBox_15.setObjectName("groupBox_15")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_15)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_15)
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.b4_elIncrement = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.b4_elIncrement.setMaximum(999.0)
        self.b4_elIncrement.setProperty("value", 30.0)
        self.b4_elIncrement.setObjectName("b4_elIncrement")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.b4_elIncrement)
        self.label_21 = QtWidgets.QLabel(self.groupBox_15)
        self.label_21.setObjectName("label_21")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.b4_elDash = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.b4_elDash.setMaximum(19999.0)
        self.b4_elDash.setProperty("value", 500.0)
        self.b4_elDash.setObjectName("b4_elDash")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.b4_elDash)
        self.label_22 = QtWidgets.QLabel(self.groupBox_15)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.b4_elMaxind = QtWidgets.QDoubleSpinBox(self.groupBox_15)
        self.b4_elMaxind.setMaximum(19999.0)
        self.b4_elMaxind.setSingleStep(100.0)
        self.b4_elMaxind.setProperty("value", 2000.0)
        self.b4_elMaxind.setObjectName("b4_elMaxind")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.b4_elMaxind)
        self.b4_doElas = QtWidgets.QPushButton(self.groupBox_15)
        self.b4_doElas.setObjectName("b4_doElas")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.b4_doElas)
        self.label_24 = QtWidgets.QLabel(self.groupBox_15)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.horizontalLayout_5.addWidget(self.groupBox_15)
        self.groupBox_20 = QtWidgets.QGroupBox(self.stackedWidgetPage3)
        self.groupBox_20.setObjectName("groupBox_20")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_20)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_29 = QtWidgets.QLabel(self.groupBox_20)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_20)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 2, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_20)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 0, 0, 1, 1)
        self.b3_labE0 = QtWidgets.QLabel(self.groupBox_20)
        self.b3_labE0.setTextFormat(QtCore.Qt.RichText)
        self.b3_labE0.setObjectName("b3_labE0")
        self.gridLayout_5.addWidget(self.b3_labE0, 0, 1, 1, 1)
        self.b3_labEb = QtWidgets.QLabel(self.groupBox_20)
        self.b3_labEb.setTextFormat(QtCore.Qt.RichText)
        self.b3_labEb.setObjectName("b3_labEb")
        self.gridLayout_5.addWidget(self.b3_labEb, 1, 1, 1, 1)
        self.b3_labd0 = QtWidgets.QLabel(self.groupBox_20)
        self.b3_labd0.setTextFormat(QtCore.Qt.RichText)
        self.b3_labd0.setObjectName("b3_labd0")
        self.gridLayout_5.addWidget(self.b3_labd0, 2, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_20)
        self.HertzianFit = QtWidgets.QGroupBox(self.stackedWidgetPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HertzianFit.sizePolicy().hasHeightForWidth())
        self.HertzianFit.setSizePolicy(sizePolicy)
        self.HertzianFit.setObjectName("HertzianFit")
        self.gridLayout = QtWidgets.QGridLayout(self.HertzianFit)
        self.gridLayout.setObjectName("gridLayout")
        self.b3_maxForce = QtWidgets.QRadioButton(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_maxForce.sizePolicy().hasHeightForWidth())
        self.b3_maxForce.setSizePolicy(sizePolicy)
        self.b3_maxForce.setObjectName("b3_maxForce")
        self.gridLayout.addWidget(self.b3_maxForce, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.HertzianFit)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 1, 3, 1, 1)
        self.b3_Eavg = QtWidgets.QLabel(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_Eavg.sizePolicy().hasHeightForWidth())
        self.b3_Eavg.setSizePolicy(sizePolicy)
        self.b3_Eavg.setTextFormat(QtCore.Qt.RichText)
        self.b3_Eavg.setObjectName("b3_Eavg")
        self.gridLayout.addWidget(self.b3_Eavg, 0, 4, 1, 1)
        self.AverageE = QtWidgets.QLabel(self.HertzianFit)
        self.AverageE.setObjectName("AverageE")
        self.gridLayout.addWidget(self.AverageE, 0, 3, 1, 1)
        self.b3_Estd = QtWidgets.QLabel(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_Estd.sizePolicy().hasHeightForWidth())
        self.b3_Estd.setSizePolicy(sizePolicy)
        self.b3_Estd.setTextFormat(QtCore.Qt.RichText)
        self.b3_Estd.setObjectName("b3_Estd")
        self.gridLayout.addWidget(self.b3_Estd, 1, 4, 1, 1)
        self.b3_threshold = QtWidgets.QDoubleSpinBox(self.HertzianFit)
        self.b3_threshold.setSuffix("")
        self.b3_threshold.setMaximum(19999.0)
        self.b3_threshold.setProperty("value", 1000.0)
        self.b3_threshold.setObjectName("b3_threshold")
        self.gridLayout.addWidget(self.b3_threshold, 0, 2, 1, 1)
        self.b3_bins = QtWidgets.QSpinBox(self.HertzianFit)
        self.b3_bins.setMaximum(999)
        self.b3_bins.setObjectName("b3_bins")
        self.gridLayout.addWidget(self.b3_bins, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 1, 1, 1)
        self.b3_doCutFit = QtWidgets.QPushButton(self.HertzianFit)
        self.b3_doCutFit.setObjectName("b3_doCutFit")
        self.gridLayout.addWidget(self.b3_doCutFit, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.HertzianFit)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 2, 3, 1, 1)
        self.b3_maxIndentation = QtWidgets.QRadioButton(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_maxIndentation.sizePolicy().hasHeightForWidth())
        self.b3_maxIndentation.setSizePolicy(sizePolicy)
        self.b3_maxIndentation.setChecked(True)
        self.b3_maxIndentation.setObjectName("b3_maxIndentation")
        self.gridLayout.addWidget(self.b3_maxIndentation, 0, 1, 1, 1)
        self.b3_results = QtWidgets.QLabel(self.HertzianFit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_results.sizePolicy().hasHeightForWidth())
        self.b3_results.setSizePolicy(sizePolicy)
        self.b3_results.setTextFormat(QtCore.Qt.RichText)
        self.b3_results.setObjectName("b3_results")
        self.gridLayout.addWidget(self.b3_results, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.HertzianFit)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 3, 1, 1)
        self.b3_ShiftCurves = QtWidgets.QPushButton(self.HertzianFit)
        self.b3_ShiftCurves.setObjectName("b3_ShiftCurves")
        self.gridLayout.addWidget(self.b3_ShiftCurves, 3, 4, 1, 1)
        self.b3_ShiftValue = QtWidgets.QSpinBox(self.HertzianFit)
        self.b3_ShiftValue.setMinimum(-99999)
        self.b3_ShiftValue.setMaximum(99999)
        self.b3_ShiftValue.setSingleStep(50)
        self.b3_ShiftValue.setObjectName("b3_ShiftValue")
        self.gridLayout.addWidget(self.b3_ShiftValue, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.HertzianFit)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.HertzianFit)
        self.ShiftArray = QtWidgets.QGroupBox(self.stackedWidgetPage3)
        self.ShiftArray.setObjectName("ShiftArray")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.ShiftArray)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.ShiftArray)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.b3_ShiftArrayFile = QtWidgets.QLineEdit(self.ShiftArray)
        self.b3_ShiftArrayFile.setObjectName("b3_ShiftArrayFile")
        self.gridLayout_3.addWidget(self.b3_ShiftArrayFile, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ShiftArray)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.b3_ShiftArrayMax = QtWidgets.QSpinBox(self.ShiftArray)
        self.b3_ShiftArrayMax.setMinimum(-99999)
        self.b3_ShiftArrayMax.setMaximum(99999)
        self.b3_ShiftArrayMax.setSingleStep(10)
        self.b3_ShiftArrayMax.setProperty("value", 500)
        self.b3_ShiftArrayMax.setObjectName("b3_ShiftArrayMax")
        self.gridLayout_3.addWidget(self.b3_ShiftArrayMax, 1, 2, 1, 1)
        self.b3_CreateCpShiftArray = QtWidgets.QPushButton(self.ShiftArray)
        self.b3_CreateCpShiftArray.setObjectName("b3_CreateCpShiftArray")
        self.gridLayout_3.addWidget(self.b3_CreateCpShiftArray, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ShiftArray)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ShiftArray)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.b3_ShiftArrayMin = QtWidgets.QSpinBox(self.ShiftArray)
        self.b3_ShiftArrayMin.setMinimum(-99999)
        self.b3_ShiftArrayMin.setMaximum(99999)
        self.b3_ShiftArrayMin.setSingleStep(10)
        self.b3_ShiftArrayMin.setProperty("value", -500)
        self.b3_ShiftArrayMin.setObjectName("b3_ShiftArrayMin")
        self.gridLayout_3.addWidget(self.b3_ShiftArrayMin, 0, 2, 1, 1)
        self.b3_ShiftArrayStep = QtWidgets.QSpinBox(self.ShiftArray)
        self.b3_ShiftArrayStep.setMaximum(99999)
        self.b3_ShiftArrayStep.setSingleStep(10)
        self.b3_ShiftArrayStep.setProperty("value", 100)
        self.b3_ShiftArrayStep.setObjectName("b3_ShiftArrayStep")
        self.gridLayout_3.addWidget(self.b3_ShiftArrayStep, 2, 2, 1, 1)
        self.horizontalLayout_5.addWidget(self.ShiftArray)
        self.b3_ShiftArrayImage = QtWidgets.QLabel(self.stackedWidgetPage3)
        self.b3_ShiftArrayImage.setText("")
        self.b3_ShiftArrayImage.setPixmap(QtGui.QPixmap("out.png"))
        self.b3_ShiftArrayImage.setObjectName("b3_ShiftArrayImage")
        self.horizontalLayout_5.addWidget(self.b3_ShiftArrayImage)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.groupBox_11 = QtWidgets.QGroupBox(self.stackedWidgetPage3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.b3_doExport = QtWidgets.QPushButton(self.groupBox_11)
        self.b3_doExport.setObjectName("b3_doExport")
        self.verticalLayout_12.addWidget(self.b3_doExport)
        self.b3_save = QtWidgets.QPushButton(self.groupBox_11)
        self.b3_save.setObjectName("b3_save")
        self.verticalLayout_12.addWidget(self.b3_save)
        self.b3_doExport2 = QtWidgets.QPushButton(self.groupBox_11)
        self.b3_doExport2.setObjectName("b3_doExport2")
        self.verticalLayout_12.addWidget(self.b3_doExport2)
        self.horizontalLayout_5.addWidget(self.groupBox_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.b3_Alpha = QtWidgets.QSlider(self.stackedWidgetPage3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3_Alpha.sizePolicy().hasHeightForWidth())
        self.b3_Alpha.setSizePolicy(sizePolicy)
        self.b3_Alpha.setMaximum(255)
        self.b3_Alpha.setProperty("value", 30)
        self.b3_Alpha.setOrientation(QtCore.Qt.Vertical)
        self.b3_Alpha.setObjectName("b3_Alpha")
        self.horizontalLayout_13.addWidget(self.b3_Alpha)
        self.b3_plotind = PlotWidget(self.stackedWidgetPage3)
        self.b3_plotind.setObjectName("b3_plotind")
        self.horizontalLayout_13.addWidget(self.b3_plotind)
        self.b3_plotscatter = PlotWidget(self.stackedWidgetPage3)
        self.b3_plotscatter.setObjectName("b3_plotscatter")
        self.horizontalLayout_13.addWidget(self.b3_plotscatter)
        self.b3_plothist = PlotWidget(self.stackedWidgetPage3)
        self.b3_plothist.setObjectName("b3_plothist")
        self.horizontalLayout_13.addWidget(self.b3_plothist)
        self.horizontalLayout_13.setStretch(1, 4)
        self.horizontalLayout_13.setStretch(2, 3)
        self.horizontalLayout_13.setStretch(3, 3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.b3_long = PlotWidget(self.stackedWidgetPage3)
        self.b3_long.setObjectName("b3_long")
        self.horizontalLayout_8.addWidget(self.b3_long)
        self.b3_plothist_E0 = PlotWidget(self.stackedWidgetPage3)
        self.b3_plothist_E0.setObjectName("b3_plothist_E0")
        self.horizontalLayout_8.addWidget(self.b3_plothist_E0)
        self.b3_plothist_Eb = PlotWidget(self.stackedWidgetPage3)
        self.b3_plothist_Eb.setObjectName("b3_plothist_Eb")
        self.horizontalLayout_8.addWidget(self.b3_plothist_Eb)
        self.b3_plothist_d0 = PlotWidget(self.stackedWidgetPage3)
        self.b3_plothist_d0.setObjectName("b3_plothist_d0")
        self.horizontalLayout_8.addWidget(self.b3_plothist_d0)
        self.horizontalLayout_8.setStretch(0, 4)
        self.horizontalLayout_8.setStretch(1, 2)
        self.horizontalLayout_8.setStretch(2, 2)
        self.horizontalLayout_8.setStretch(3, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.switcher.addWidget(self.stackedWidgetPage3)
        self.verticalLayout_3.addWidget(self.switcher)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.switcher.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nano2020"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Limits"))
        self.label_10.setText(_translate("MainWindow", "Max"))
        self.label_9.setText(_translate("MainWindow", "Min"))
        self.groupBox_7.setTitle(_translate("MainWindow", "yAlign"))
        self.b1_yAlignButton.setText(_translate("MainWindow", "yAlign"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Cutting"))
        self.b1_doInvalidate.setText(_translate("MainWindow", "Invalidate"))
        self.groupBox.setTitle(_translate("MainWindow", "View"))
        self.b1_redblack.setText(_translate("MainWindow", "All"))
        self.b1_black.setText(_translate("MainWindow", "Black"))
        self.b1_red.setText(_translate("MainWindow", "Red"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Open"))
        self.open_o11new.setText(_translate("MainWindow", "Optics11 - NEW"))
        self.open_o11old.setText(_translate("MainWindow", "Optics11 - OLD"))
        self.open_nanosurf.setText(_translate("MainWindow", "Nanosurf export"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Actions"))
        self.b1tob2.setText(_translate("MainWindow", ">>>"))
        self.b1tob2.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.b1_generate.setText(_translate("MainWindow", "Generate"))
        self.sl_load.setText(_translate("MainWindow", "Load"))
        self.sl_load.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.b1_selectFolder.setText(_translate("MainWindow", "Select Root Folder"))
        self.b1_selectFolder.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.b1_mainList.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.groupBox_2.setTitle(_translate("MainWindow", "View"))
        self.b2_vOriginal.setText(_translate("MainWindow", "Original"))
        self.b2_vFiltered.setText(_translate("MainWindow", "Filtered"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Actions"))
        self.b2_save.setText(_translate("MainWindow", "Save"))
        self.b2_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.b2_b2tob3.setText(_translate("MainWindow", ">>>"))
        self.b2_b2tob3.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.b2_delete.setText(_translate("MainWindow", "Delete"))
        self.b2_delete.setShortcut(_translate("MainWindow", "Del"))
        self.b2_deleteAllInvalid.setText(_translate("MainWindow", "Remove All Invalid"))
        self.b2_deleteAllInvalid.setShortcut(_translate("MainWindow", "Ctrl+Del"))
        self.b2_CropCurves.setText(_translate("MainWindow", "Crop Curves"))
        self.b2_doFilter.setText(_translate("MainWindow", "Filter"))
        self.b2_doFilter.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Contact point"))
        self.comboContact.setItemText(0, _translate("MainWindow", "eeff"))
        self.comboContact.setItemText(1, _translate("MainWindow", "Nanosurf Deriv"))
        self.comboContact.setItemText(2, _translate("MainWindow", "Nanosurf"))
        self.comboContact.setItemText(3, _translate("MainWindow", "Chiaro"))
        self.b2_doContactPoint.setText(_translate("MainWindow", "Execute"))
        self.b2_doContactPoint.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.b2_DoElasto.setText(_translate("MainWindow", "Do Elastography"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Elastography"))
        self.label_20.setText(_translate("MainWindow", "Increment"))
        self.label_21.setText(_translate("MainWindow", "Dash depth"))
        self.label_22.setText(_translate("MainWindow", "Max indent"))
        self.b4_doElas.setText(_translate("MainWindow", "Elastography"))
        self.b4_doElas.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.label_24.setText(_translate("MainWindow", "O"))
        self.groupBox_20.setTitle(_translate("MainWindow", "E-FIT"))
        self.label_29.setText(_translate("MainWindow", "Eb"))
        self.label_30.setText(_translate("MainWindow", "d0"))
        self.label_28.setText(_translate("MainWindow", "E0"))
        self.b3_labE0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> Pa</p></body></html>"))
        self.b3_labEb.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> Pa</p></body></html>"))
        self.b3_labd0.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> nm</p></body></html>"))
        self.HertzianFit.setTitle(_translate("MainWindow", "Hertzian Fit"))
        self.b3_maxForce.setText(_translate("MainWindow", "Force"))
        self.label_11.setText(_translate("MainWindow", "Std E"))
        self.b3_Eavg.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> Pa</p></body></html>"))
        self.AverageE.setText(_translate("MainWindow", "Average E"))
        self.b3_Estd.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> Pa</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Bins"))
        self.b3_doCutFit.setText(_translate("MainWindow", "Fit"))
        self.b3_doCutFit.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.label_14.setText(_translate("MainWindow", "E"))
        self.b3_maxIndentation.setText(_translate("MainWindow", "Indentation"))
        self.b3_results.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">N/A</span> Pa</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "nm"))
        self.b3_ShiftCurves.setText(_translate("MainWindow", "Shift"))
        self.label.setText(_translate("MainWindow", "Shift all curves"))
        self.ShiftArray.setTitle(_translate("MainWindow", "Shift Array (normalized individually, data starting from dash depth)"))
        self.label_5.setText(_translate("MainWindow", "Max Shift"))
        self.b3_ShiftArrayFile.setText(_translate("MainWindow", "test"))
        self.label_3.setText(_translate("MainWindow", "file name"))
        self.b3_CreateCpShiftArray.setText(_translate("MainWindow", "Create CP shift array"))
        self.label_4.setText(_translate("MainWindow", "Min Shift"))
        self.label_6.setText(_translate("MainWindow", "Step Size"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Actions"))
        self.b3_doExport.setText(_translate("MainWindow", "Export Single"))
        self.b3_doExport.setShortcut(_translate("MainWindow", "Ctrl+E, Ctrl+S"))
        self.b3_save.setText(_translate("MainWindow", "Save"))
        self.b3_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.b3_doExport2.setText(_translate("MainWindow", "Export Bilayer"))
        self.b3_doExport2.setShortcut(_translate("MainWindow", "Ctrl+E, Ctrl+B"))
from pyqtgraph import PlotWidget
