# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtView.ui'
#
# Created: Tue Mar 10 18:45:33 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_facewindow(object):
    def setupUi(self, facewindow):
        facewindow.setObjectName(_fromUtf8("facewindow"))
        facewindow.resize(1187, 673)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../git/SiMPlE/smfsmanager/D_mica.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        facewindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(facewindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.grafo = PlotWidget(self.centralwidget)
        self.grafo.setGeometry(QtCore.QRect(0, 0, 751, 551))
        self.grafo.setToolTip(_fromUtf8(""))
        self.grafo.setStatusTip(_fromUtf8(""))
        self.grafo.setWhatsThis(_fromUtf8(""))
        self.grafo.setObjectName(_fromUtf8("grafo"))
        self.slide1 = QtGui.QScrollBar(self.centralwidget)
        self.slide1.setEnabled(True)
        self.slide1.setGeometry(QtCore.QRect(750, 0, 16, 551))
        self.slide1.setMinimum(1)
        self.slide1.setMaximum(1)
        self.slide1.setTracking(False)
        self.slide1.setOrientation(QtCore.Qt.Vertical)
        self.slide1.setObjectName(_fromUtf8("slide1"))
        self.slide2 = QtGui.QDial(self.centralwidget)
        self.slide2.setEnabled(True)
        self.slide2.setGeometry(QtCore.QRect(790, 555, 71, 71))
        self.slide2.setMinimum(1)
        self.slide2.setMaximum(1)
        self.slide2.setTracking(True)
        self.slide2.setObjectName(_fromUtf8("slide2"))
        self.griglia = QtGui.QGraphicsView(self.centralwidget)
        self.griglia.setEnabled(True)
        self.griglia.setGeometry(QtCore.QRect(770, 10, 121, 511))
        self.griglia.setObjectName(_fromUtf8("griglia"))
        self.labFilename = QtGui.QLabel(self.centralwidget)
        self.labFilename.setGeometry(QtCore.QRect(480, 10, 261, 16))
        self.labFilename.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labFilename.setObjectName(_fromUtf8("labFilename"))
        self.slide3 = QtGui.QSpinBox(self.centralwidget)
        self.slide3.setGeometry(QtCore.QRect(770, 524, 121, 27))
        self.slide3.setMinimum(1)
        self.slide3.setMaximum(1)
        self.slide3.setObjectName(_fromUtf8("slide3"))
        self.bAddFiles = QtGui.QPushButton(self.centralwidget)
        self.bAddFiles.setGeometry(QtCore.QRect(650, 560, 89, 27))
        self.bAddFiles.setObjectName(_fromUtf8("bAddFiles"))
        self.bAddDir = QtGui.QPushButton(self.centralwidget)
        self.bAddDir.setGeometry(QtCore.QRect(650, 590, 89, 27))
        self.bAddDir.setObjectName(_fromUtf8("bAddDir"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 560, 171, 91))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.derorder = QtGui.QSpinBox(self.groupBox)
        self.derorder.setGeometry(QtCore.QRect(120, 50, 48, 27))
        self.derorder.setMaximum(10)
        self.derorder.setProperty("value", 1)
        self.derorder.setObjectName(_fromUtf8("derorder"))
        self.segment = QtGui.QCheckBox(self.groupBox)
        self.segment.setGeometry(QtCore.QRect(120, 20, 41, 22))
        self.segment.setObjectName(_fromUtf8("segment"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 102, 52))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_view = QtGui.QRadioButton(self.layoutWidget)
        self.radio_view.setStyleSheet(_fromUtf8("border: none;"))
        self.radio_view.setChecked(True)
        self.radio_view.setObjectName(_fromUtf8("radio_view"))
        self.buttonGroup = QtGui.QButtonGroup(facewindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.radio_view)
        self.verticalLayout_2.addWidget(self.radio_view)
        self.radio_deriv = QtGui.QRadioButton(self.layoutWidget)
        self.radio_deriv.setStyleSheet(_fromUtf8("border: none;"))
        self.radio_deriv.setObjectName(_fromUtf8("radio_deriv"))
        self.buttonGroup.addButton(self.radio_deriv)
        self.verticalLayout_2.addWidget(self.radio_deriv)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 560, 451, 91))
        self.groupBox_2.setStyleSheet(_fromUtf8("border: none;"))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 431, 71))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.sg_mm = QtGui.QSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.sg_mm.setFont(font)
        self.sg_mm.setStyleSheet(_fromUtf8("border: none;"))
        self.sg_mm.setMinimum(-90)
        self.sg_mm.setMaximum(90)
        self.sg_mm.setProperty("value", 45)
        self.sg_mm.setObjectName(_fromUtf8("sg_mm"))
        self.gridLayout.addWidget(self.sg_mm, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("border: none;"))
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.s_vth = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.s_vth.setFont(font)
        self.s_vth.setStyleSheet(_fromUtf8("border: none;"))
        self.s_vth.setMaximum(9999.0)
        self.s_vth.setSingleStep(0.1)
        self.s_vth.setProperty("value", 10.0)
        self.s_vth.setObjectName(_fromUtf8("s_vth"))
        self.gridLayout.addWidget(self.s_vth, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("border: none;"))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("border: none;"))
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("border: none;"))
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.s_mth = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.s_mth.setFont(font)
        self.s_mth.setStyleSheet(_fromUtf8("border: none;"))
        self.s_mth.setDecimals(3)
        self.s_mth.setMaximum(1000.0)
        self.s_mth.setSingleStep(0.1)
        self.s_mth.setProperty("value", 1.5)
        self.s_mth.setObjectName(_fromUtf8("s_mth"))
        self.gridLayout.addWidget(self.s_mth, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        font.setKerning(True)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("border: none;"))
        self.label_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_5.setLineWidth(1)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 4, 1, 1)
        self.plath = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.plath.setFont(font)
        self.plath.setMinimum(-100000.0)
        self.plath.setMaximum(100000.0)
        self.plath.setProperty("value", 3000.0)
        self.plath.setObjectName(_fromUtf8("plath"))
        self.gridLayout.addWidget(self.plath, 0, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("border: none;"))
        self.label_6.setLineWidth(1)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 4, 1, 1)
        self.lasth = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.lasth.setFont(font)
        self.lasth.setMaximum(1000.0)
        self.lasth.setProperty("value", 5.0)
        self.lasth.setObjectName(_fromUtf8("lasth"))
        self.gridLayout.addWidget(self.lasth, 1, 5, 1, 1)
        self.sg_fw = QtGui.QDoubleSpinBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Verdana"))
        font.setPointSize(8)
        self.sg_fw.setFont(font)
        self.sg_fw.setStyleSheet(_fromUtf8("border: none;"))
        self.sg_fw.setMinimum(0.01)
        self.sg_fw.setMaximum(99.99)
        self.sg_fw.setSingleStep(0.1)
        self.sg_fw.setProperty("value", 0.5)
        self.sg_fw.setObjectName(_fromUtf8("sg_fw"))
        self.gridLayout.addWidget(self.sg_fw, 0, 3, 1, 1)
        self.isto = PlotWidget(self.centralwidget)
        self.isto.setGeometry(QtCore.QRect(900, 10, 281, 251))
        self.isto.setToolTip(_fromUtf8(""))
        self.isto.setStatusTip(_fromUtf8(""))
        self.isto.setWhatsThis(_fromUtf8(""))
        self.isto.setObjectName(_fromUtf8("isto"))
        self.scatter = PlotWidget(self.centralwidget)
        self.scatter.setGeometry(QtCore.QRect(900, 310, 281, 241))
        self.scatter.setToolTip(_fromUtf8(""))
        self.scatter.setStatusTip(_fromUtf8(""))
        self.scatter.setWhatsThis(_fromUtf8(""))
        self.scatter.setObjectName(_fromUtf8("scatter"))
        self.cIsto = QtGui.QComboBox(self.centralwidget)
        self.cIsto.setGeometry(QtCore.QRect(900, 270, 181, 27))
        self.cIsto.setEditable(False)
        self.cIsto.setObjectName(_fromUtf8("cIsto"))
        self.cIsto.addItem(_fromUtf8(""))
        self.cIsto.addItem(_fromUtf8(""))
        self.cIsto.addItem(_fromUtf8(""))
        self.bStat = QtGui.QPushButton(self.centralwidget)
        self.bStat.setGeometry(QtCore.QRect(900, 590, 89, 27))
        self.bStat.setObjectName(_fromUtf8("bStat"))
        self.cScatter = QtGui.QComboBox(self.centralwidget)
        self.cScatter.setGeometry(QtCore.QRect(900, 560, 281, 27))
        self.cScatter.setEditable(False)
        self.cScatter.setObjectName(_fromUtf8("cScatter"))
        self.cScatter.addItem(_fromUtf8(""))
        self.cScatter.addItem(_fromUtf8(""))
        self.cScatter.addItem(_fromUtf8(""))
        self.nBins = QtGui.QSpinBox(self.centralwidget)
        self.nBins.setGeometry(QtCore.QRect(1107, 270, 71, 27))
        self.nBins.setMinimum(1)
        self.nBins.setMaximum(1000)
        self.nBins.setProperty("value", 20)
        self.nBins.setObjectName(_fromUtf8("nBins"))
        self.bClear = QtGui.QPushButton(self.centralwidget)
        self.bClear.setGeometry(QtCore.QRect(650, 620, 89, 27))
        self.bClear.setObjectName(_fromUtf8("bClear"))
        self.bFreeze = QtGui.QPushButton(self.centralwidget)
        self.bFreeze.setGeometry(QtCore.QRect(1120, 10, 61, 27))
        self.bFreeze.setObjectName(_fromUtf8("bFreeze"))
        self.bSSave = QtGui.QPushButton(self.centralwidget)
        self.bSSave.setGeometry(QtCore.QRect(990, 590, 89, 27))
        self.bSSave.setObjectName(_fromUtf8("bSSave"))
        self.labDetails = QtGui.QLabel(self.centralwidget)
        self.labDetails.setGeometry(QtCore.QRect(0, 20, 741, 20))
        self.labDetails.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labDetails.setObjectName(_fromUtf8("labDetails"))
        facewindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(facewindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1187, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        facewindow.setMenuBar(self.menubar)

        self.retranslateUi(facewindow)
        self.cIsto.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(facewindow)

    def retranslateUi(self, facewindow):
        facewindow.setWindowTitle(_translate("facewindow", "MainWindow", None))
        self.labFilename.setText(_translate("facewindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">FILENAME</span></p></body></html>", None))
        self.bAddFiles.setText(_translate("facewindow", "Add Files", None))
        self.bAddDir.setText(_translate("facewindow", "Add DIR", None))
        self.groupBox.setTitle(_translate("facewindow", "View", None))
        self.segment.setText(_translate("facewindow", "S", None))
        self.radio_view.setText(_translate("facewindow", "Curve", None))
        self.radio_deriv.setText(_translate("facewindow", "Derivative", None))
        self.label_4.setText(_translate("facewindow", "Slope (°)", None))
        self.label.setText(_translate("facewindow", "Thresh (std)", None))
        self.label_2.setText(_translate("facewindow", "MinLen [nm]", None))
        self.label_3.setText(_translate("facewindow", "Window", None))
        self.label_5.setText(_translate("facewindow", "Zdist [nm]", None))
        self.label_6.setText(_translate("facewindow", "LastTH [pN]", None))
        self.cIsto.setItemText(0, _translate("facewindow", "Length", None))
        self.cIsto.setItemText(1, _translate("facewindow", "Number", None))
        self.cIsto.setItemText(2, _translate("facewindow", "Step", None))
        self.bStat.setText(_translate("facewindow", "Do stats", None))
        self.cScatter.setItemText(0, _translate("facewindow", "Length vs Position", None))
        self.cScatter.setItemText(1, _translate("facewindow", "Step vs Position", None))
        self.cScatter.setItemText(2, _translate("facewindow", "Step vs Length", None))
        self.bClear.setText(_translate("facewindow", "Clear ALL", None))
        self.bFreeze.setText(_translate("facewindow", "Freeze", None))
        self.bSSave.setText(_translate("facewindow", "Save stats", None))
        self.labDetails.setText(_translate("facewindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">xxx</p></body></html>", None))

from pyqtgraph import PlotWidget
